// Code generated by entc, DO NOT EDIT.

package ent

import "kratos-practice/internal/biz"

func (cu *CarUpdate) SetCar(input *biz.Car) *CarUpdate {

	cu.SetNillableUserID(input.UserID)

	cu.SetNillableModel(input.Model)

	cu.SetNillableRegisteredAt(input.RegisteredAt)
	return cu
}

func (cc *CarCreate) SetCar(input *biz.Car) *CarCreate {

	cc.SetNillableUserID(input.UserID)

	cc.SetNillableModel(input.Model)

	cc.SetNillableRegisteredAt(input.RegisteredAt)
	return cc
}

func (uu *UserUpdate) SetUser(input *biz.User) *UserUpdate {

	uu.SetNillableUsername(input.Username)

	uu.SetNillablePassword(input.Password)

	uu.SetNillableCreatedAt(input.CreatedAt)

	uu.SetNillableUpdatedAt(input.UpdatedAt)
	return uu
}

func (uc *UserCreate) SetUser(input *biz.User) *UserCreate {

	uc.SetNillableUsername(input.Username)

	uc.SetNillablePassword(input.Password)

	uc.SetNillableCreatedAt(input.CreatedAt)

	uc.SetNillableUpdatedAt(input.UpdatedAt)
	return uc
}
