trace:
  endpoint: 127.0.0.1:4317

metric:
  endpoint: 127.0.0.1:4317

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:root@tcp(192.168.31.96:3306)/test?parseTime=true
  redis:
    addr: 192.168.31.96:6379
    password: admin
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  file: /data/logs/app.logs